TerryHowe/ansible-modules-hashivault

ansible/module_utils/hashivault.py
ansible/plugins/lookup/hashivault.py

I took the liberty to implement dmaze's proposed changes from issue #12, since we have the same issue.
I also took the liberty to rename his function so it fits the naming of the other functions.

Try to get default token also from ~/.vault-token

---

functional/start.sh

Disable mlock, so no IPC_LOCK should be needed
It also waits now for docker to be healthy instead of just for the open port.
And some other refactorizations in start script to increase readability.

Fix test runner for travis

---

ansible/modules/hashivault/hashivault_delete.py
functional/test_secret.yml

Add delete secret capability

---

ansible/modules/hashivault/hashivault_seal.py
ansible/modules/hashivault/hashivault_unseal.py
functional/test_unseal.yml

un/seal check if it has to be un/sealed before doing it
this gives back a correct ansible change status

make it possible to add handlers on un/seal action

---

README.rst

This addressed : issue #70 
I find your repo very helpful, the least I can do is help with some of the documentation

improved documentation about export variables

---

ansible/modules/hashivault/hashivault_aws_role_create.py
functional/run.sh
functional/test_create_ec2_role.yml

This new feature will allow to create new aws backed auth roles.

allows to create a aws ec2 backed vault role

---

ansible/module_utils/hashivault.py

This PR will allow uses of this module to use AWS IAM Auth to authenticate against vault and get a vault token.

Feature - support aws iam authenication against vault 

---

README.rst
ansible/modules/hashivault/hashivault_token_renew.py
ansible/modules/hashivault/hashivault_token_revoke.py

Added hashivault_token_renew and hashivault_token_revoke functions for renewing and revoking tokens.

added token renew and token revoke functions

---

ansible/modules/hashivault/hashivault_identity_entity.py

Add identity module.
Functions:
- Create/Update/Delete entities in identity engine

Add identity management module

---

ansible/modules/hashivault/hashivault_approle_role_secret_create.py

* Updated module documentation.
* Added an example to illustrate usage.
* Added optional parameter `secret_id` representing custom SecretID that is set against an AppRole by the client in the Push mode. For further info see: https://www.vaultproject.io/docs/auth/approle.html#secretid
* Now depending whether on `secret_id` is defined for module Ansible will fetch the SecretID in Pull mode if it is not and send the custom SecretID to Vault in Push mode if it is.

Allow to create custom approle secret id

---

ansible/modules/hashivault/hashivault_db_secret_engine_role.py

Signed-off-by: Damien Goldenberg <damdam.gold@gmail.com>
related to #142

Fix the compatibility of the db role module with python 2.7

---

ansible/modules/hashivault/hashivault_db_secret_engine_config.py
functional/test_db_config.yml

Signed-off-by: Damien Goldenberg <damdam.gold@gmail.com>

db engine config plugin can be used for all db plugins

---

ansible/modules/hashivault/hashivault_ldap_group.py
functional/run.sh
functional/test_ldap_group.yml

Added a module to add LDAP groups

Added a module to add ldap groups

---

ansible/modules/hashivault/hashivault_approle_role.py
ansible/modules/hashivault/hashivault_approle_role_secret.py
functional/test_approle.yml

Add check_mode support for approle

---

ansible/modules/hashivault/hashivault_approle_role.py

create an optional param `role_file` that can accept an approles params to be defined in a file

approle can accept params in a file with role_file

---

ansible/modules/hashivault/_hashivault_policy_set_from_file.py
ansible/modules/hashivault/hashivault_policy_set.py
functional/test_policy.yml

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/160

Deprecate hashivault_policy_set_from_file

---

ansible/modules/hashivault/hashivault_write.py

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/179

Provide logged alternate data for write to get returned data

---

ansible/modules/hashivault/hashivault_oidc_auth_role.py

This solved multiple issues with the "policies" parameter being undefined when calling the API, PEP 8 issues, "change" state misbehavior, and ca_cert/ca_path usage

Refactored the oidc_auth_role module

---

ansible/modules/hashivault/hashivault_identity_group_alias.py

Add the module for managing group aliases + fix typo in entity_alias

Add the module for managing group aliases + fix typo in entity_alias

---

ansible/modules/hashivault/hashivault_userpass.py
functional/run.sh
functional/test_userpass_idempotent.yml
functional/test_userpass_no_pass.yml

Add logic and tests for setting token_bound_cidrs in hashivault_userpass.

Add support for token_bound_cidrs in hashivault_userpass

---

ansible/modules/hashivault/hashivault_userpass.py

mount_point should be passed when userpass is created

userpass: pass mount_point on create, too

---

ansible/modules/hashivault/hashivault_k8s_auth_config.py

Added kubernetes auth method

---

ansible/modules/hashivault/hashivault_identity_group.py
ansible/modules/hashivault/hashivault_secret_engine.py
ansible/modules/hashivault/hashivault_write.py
functional/test_identity_group.yml

https://github.com/TerryHowe/ansible-modules-hashivault/issues/212

Fix for hvac 0.10.1

---

README.rst
ansible/module_utils/hashivault.py
ansible/plugins/doc_fragments/hashivault.py
ansible/plugins/lookup/hashivault.py

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/153

Add aws header for auth

---

ansible/modules/hashivault/hashivault_azure_auth_config.py
ansible/modules/hashivault/hashivault_azure_auth_role.py
ansible/modules/hashivault/hashivault_azure_secret_engine_config.py
ansible/modules/hashivault/hashivault_azure_secret_engine_role.py
ansible/modules/hashivault/hashivault_db_secret_engine_config.py
ansible/modules/hashivault/hashivault_db_secret_engine_role.py
ansible/modules/hashivault/hashivault_k8s_auth_config.py
ansible/modules/hashivault/hashivault_k8s_auth_role.py
ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
ansible/modules/hashivault/hashivault_oidc_auth_role.py

Get more consistent on mount_point handling

---

ansible/modules/hashivault/_hashivault_auth_enable.py
ansible/modules/hashivault/hashivault_auth_ldap.py
ansible/modules/hashivault/hashivault_auth_method.py
ansible/modules/hashivault/hashivault_aws_ec2_role_create.py
ansible/modules/hashivault/hashivault_azure_auth_config.py
ansible/modules/hashivault/hashivault_azure_auth_role.py
ansible/modules/hashivault/hashivault_k8s_auth_config.py
ansible/modules/hashivault/hashivault_k8s_auth_role.py
ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
ansible/modules/hashivault/hashivault_oidc_auth_role.py
functional/test_auth_method.yml

Be consistent on list auth methods

---

ansible/modules/hashivault/hashivault_k8s_auth_config.py

https://github.com/TerryHowe/ansible-modules-hashivault/issues/236

Add pem_keys support to k8s

---

ansible/modules/hashivault/hashivault_consul_secret_engine_config.py
ansible/modules/hashivault/hashivault_consul_secret_engine_role.py
functional/run.sh
functional/test_consul_config.yml
functional/test_consul_role.yml
setup.py

Add support for [consul secret engine](https://www.vaultproject.io/api/secret/consul/index.html)

Consul secret engine

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_pki_ca.py
ansible/modules/hashivault/hashivault_pki_ca_set.py
ansible/modules/hashivault/hashivault_pki_cert_issue.py
ansible/modules/hashivault/hashivault_pki_cert_list.py
ansible/modules/hashivault/hashivault_pki_cert_read.py
ansible/modules/hashivault/hashivault_pki_cert_revoke.py
ansible/modules/hashivault/hashivault_pki_cert_sign.py
ansible/modules/hashivault/hashivault_pki_crl_read.py
ansible/modules/hashivault/hashivault_pki_crl_rotate.py
ansible/modules/hashivault/hashivault_pki_crl_set.py
ansible/modules/hashivault/hashivault_pki_role.py
ansible/modules/hashivault/hashivault_pki_role_list.py
ansible/modules/hashivault/hashivault_pki_role_read.py
ansible/modules/hashivault/hashivault_pki_set_signed.py
ansible/modules/hashivault/hashivault_pki_tidy.py
ansible/modules/hashivault/hashivault_pki_url_read.py
ansible/modules/hashivault/hashivault_pki_url_set.py
functional/run.sh
functional/test_pki.yml

Hi,
I just felt like implementing PKI module.... so here they are

PKI modules

---

ansible/modules/hashivault/hashivault_pki_cert_get.py
ansible/modules/hashivault/hashivault_pki_crl.py
ansible/modules/hashivault/hashivault_pki_crl_get.py
ansible/modules/hashivault/hashivault_pki_role_get.py
ansible/modules/hashivault/hashivault_pki_url.py
ansible/modules/hashivault/hashivault_pki_url_get.py
functional/test_pki.yml

Standardize names of some pki modules

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_auth_ldap.py
ansible/modules/hashivault/hashivault_aws_auth_config.py
ansible/modules/hashivault/hashivault_aws_auth_role.py
ansible/modules/hashivault/hashivault_azure_auth_config.py
ansible/modules/hashivault/hashivault_azure_auth_role.py
ansible/modules/hashivault/hashivault_k8s_auth_config.py
ansible/modules/hashivault/hashivault_k8s_auth_role.py
ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
ansible/modules/hashivault/hashivault_oidc_auth_role.py
functional/test_k8_auth.yml
functional/test_pki.yml

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/244

Do not use sys.auth to check exists

---

ansible/modules/hashivault/hashivault_k8s_auth_config.py
functional/test_k8_auth.yml

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/236

Add issuer to k8s config

---

ansible/modules/hashivault/hashivault_policy.py

Document that state can be used to remove a policy.

Add state documentation to policy

---

setup.py

Fix for this issue #https://github.com/TerryHowe/ansible-modules-hashivault/issues/241

FIX: error with ansible-doc unknown doc-fragment hashivault

---

ansible/modules/hashivault/hashivault_pki_ca_set.py

Fix response 204 on pki_ca_set

---

ansible/modules/hashivault/hashivault_approle_role_secret_get.py
functional/test_approle.yml

hashivault_approle_role_secret_get should handle not existing secrets

Handle not existing approle role secret

---

ansible/module_utils/hashivault.py
makedocs.sh

Update argspec to use fallback

---

ansible/modules/hashivault/hashivault_aws_auth_config.py
ansible/modules/hashivault/hashivault_aws_auth_role.py

Fix incorrect aws module names

---

ansible/modules/hashivault/hashivault_secret_engine.py
ansible/modules/hashivault/hashivault_write.py
functional/run.sh
functional/test_cas.yml
functional/test_kv2.yml

Resolves https://github.com/TerryHowe/ansible-modules-hashivault/issues/275

Add cas support for write and configuration

---

ansible/modules/hashivault/hashivault_read_to_file.py
ansible/plugins/action/hashivault_read_to_file.py
functional/test_read_write_file.yml

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/271

Better error message for base64 error

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_azure_secret_engine_config.py
ansible/modules/hashivault/hashivault_azure_secret_engine_role.py
ansible/modules/hashivault/hashivault_db_secret_engine_config.py
ansible/modules/hashivault/hashivault_db_secret_engine_role.py
ansible/modules/hashivault/hashivault_pki_ca.py
ansible/modules/hashivault/hashivault_pki_ca_set.py
ansible/modules/hashivault/hashivault_pki_cert_get.py
ansible/modules/hashivault/hashivault_pki_cert_issue.py
ansible/modules/hashivault/hashivault_pki_cert_list.py
ansible/modules/hashivault/hashivault_pki_cert_revoke.py
ansible/modules/hashivault/hashivault_pki_cert_sign.py
ansible/modules/hashivault/hashivault_pki_crl.py
ansible/modules/hashivault/hashivault_pki_crl_get.py
ansible/modules/hashivault/hashivault_pki_crl_rotate.py
ansible/modules/hashivault/hashivault_pki_role.py
ansible/modules/hashivault/hashivault_pki_role_get.py
ansible/modules/hashivault/hashivault_pki_role_list.py
ansible/modules/hashivault/hashivault_pki_set_signed.py
ansible/modules/hashivault/hashivault_pki_tidy.py
ansible/modules/hashivault/hashivault_pki_url.py
ansible/modules/hashivault/hashivault_pki_url_get.py

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/274

Remove sys calls to modules that might not have access

---

ansible/modules/hashivault/hashivault_identity_group_alias.py

Fix typo.
Reference:
- https://github.com/hvac/hvac/blob/v0.10.5/hvac/api/secrets_engines/identity.py#L858

Fix function to update identity group alias

---

ansible/modules/hashivault/hashivault_approle_role_secret.py

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/283

Fix incompatible approle parameter

---

ansible/modules/hashivault/hashivault_oidc_auth_role.py
ansible/modules/hashivault/hashivault_pki_role.py

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/284

Fix pki role for int

---

ansible/modules/hashivault/hashivault_delete.py
ansible/modules/hashivault/hashivault_secret.py
ansible/modules/hashivault/hashivault_write.py
functional/run.sh
functional/test_secret.yml

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/254

Add hashivault_secret

---

ansible/plugins/lookup/hashivault.py
functional/test_list.yml
functional/test_lookup.yml

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/250

Have lookup plugin use argspec

---

ansible/module_utils/hashivault.py

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/300

Get rid of warning suppression

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_secret.py
functional/test_secret.yml

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/302

Add update support to hashivault_secret

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_read.py
functional/test_kv2.yml

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/304

secret version for read

---

ansible/modules/hashivault/hashivault_list.py
functional/test_list.yml

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/306

Add metadata read to kv2 list

---

ansible/modules/hashivault/hashivault_write.py

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/308

Use v1 call for hashivault_write

---

README.rst
ansible/modules/hashivault/hashivault_secret.py
ansible/plugins/lookup/hashivault.py

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/309

Update docs for hashivault_secret and lookup

---

ansible/module_utils/hashivault.py

Fixes https://github.com/TerryHowe/ansible-modules-hashivault/issues/332

Updated approle authentication

---

ansible/modules/hashivault/hashivault_list.py
functional/test_list.yml

Signed-off-by: Lord-Y <Lord-Y@users.noreply.github.com>
Hello guys,
Just fixing PR https://github.com/TerryHowe/ansible-modules-hashivault/pull/325
The last test want to list a folder but the full subpath is provided.

Fix unit testing for PR #325

---

ansible/modules/hashivault/hashivault_list.py

Here's my proposal to solve #324 
I'm not familiar with "metadata" so I'm not 100% sure of the solution. But I've tested the solution against a v2 keystore with success.

Allow to list secrets in subpath (issue #324)

---

ansible/modules/hashivault/hashivault_pki_role.py
functional/test_pki.yml

Fix pki role not_before_duration

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_userpass.py
functional/test_userpass.yml

Replace deprecated hvac userpass methods

---

ansible/modules/hashivault/hashivault_secret_engine.py

The `default_lease_ttl` and `max_lease_ttl` parameters in
hashivault_secret_engine can take either an integer or a string with a
duration suffix. This mimics what Vault API's `PUT /sys/mounts/:path`
accepts. However, `GET /sys/mounts/:path` always return an integer (ie.
string durations are converted into an integer).
Because of that, hashivault_secret_engine module isn't idempotent when
string durations or string containing only an integer is passed to it.
Note that the latter case happens when this value comes from a variable
(eg. a dict representing multiple engines to mount).
This fix converts aforementioned parameters into integer before
comparing them with actual values. It also changes the doc to state
only integers are accepted and why so.
Signed-off-by: Albin Kerouanton …

Transform lease TTLs into ints

---

ansible/modules/hashivault/hashivault_db_secret_engine_config.py

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/381

no-log for hashivault_db_secret_engine_config

---

ansible/modules/hashivault/hashivault_secret.py

I want existing secrets to be updated and if secret is not yet exists I want it to be created.
Prior to this changes the only possible way was to create task which lists existing secrets, another task to create new secrets and third one to update existing secrets. Which is not really convenient.

Allow create nonexistent secret when state is update

---

ansible/module_utils/hashivault.py
functional/test_write.yml

Fixes #401
I'm no python expert but here's my guess on a fix.

Fix state comparison of lists

---

ansible/modules/hashivault/hashivault_token_renew.py

Closes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/343

Add self_renew for hashivault_token_renew

---

tox.ini

replace whitelist_externals with allowlist_externals

---

ansible/modules/hashivault/hashivault_secret_engine.py

fixes #429
also removes the duplicate backend definition.

Secret engine diff

---

ansible/modules/hashivault/hashivault_auth_method.py

Auth method diff & return result

---

ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
ansible/modules/hashivault/hashivault_oidc_auth_role.py

add diff to oidc_auth modules

---

ansible/modules/hashivault/hashivault_policy.py

Refactor hashivault_policy. Now supports check and diff mode and has the same structure as other modules to determine whether to change or not. fixes #437

refactor policy module

---

ansible/modules/hashivault/hashivault_db_secret_engine_config.py

Ref https://github.com/TerryHowe/ansible-modules-hashivault/issues/442

Add plugin_version params for the vault api

---

ansible/module_utils/hashivault.py
ansible/modules/hashivault/hashivault_pki_role.py
ansible/modules/hashivault/hashivault_ssh_role.py
ansible/modules/hashivault/hashivault_token_role.py

Followup for 6cffb8d6deed7b01e1109b86395e6569b758d309. I can't figure out how to run the tests from my machine so here I am 😇

ssh_role,token_role: don't fail when encountering unknown options

---

ansible/modules/hashivault/hashivault_init.py

Closes https://github.com/TerryHowe/ansible-modules-hashivault/issues/428
Relates to https://github.com/TerryHowe/ansible-modules-hashivault/issues/116#issuecomment-1896654342
This change is backward compatible.
Add new option `seal_method` that defaults to `secret` and which allows to use `secret_*` options and disallow  `recovery_*` options.
From my understanding you can't use both otherwise you'll get an error from the API as seen in the above linked issues.
- The formatting is a bit different but I don't have time to setup myself to have something different.
I made sure old code was not impacted by my formatter
- I didn't see any tests added by https://github.com/TerryHowe/ansible-modules-hashivault/issues/116 so I did not bother adding some but I at least took the time to verify that …

Add option in hashivault_init to pass only `secret_*` or `recovery_*` options

---

ansible/modules/hashivault/hashivault_k8s_auth_role.py

Fix hashivault_k8s_auth_role not detecting policy changes

---

ansible/modules/hashivault/hashivault_auth_list.py
functional/test_auth.yml

Added few tests on top of that

Add check mode support to hashivault_auth_list
