ansible/modules/hashivault/hashivault_list.py, functional/test.yml
This adds a `hashivault_list` command, replicating the `vault list` command-line request.
This is parallel to the other `hashivault_*_list` commands that already exist.  In my particular case, I want to keep a "directory" of related credentials in Vault and iterate through them.
=> Add a hashivault_list command.

ansible/module_utils/hashivault.py
Hi,
Ansible has a way to hide passwords/sensitive values which are used as args for modules. I've set the token and password as such. This way they will not display value but a place-holder when you use high verbosity.
For example:
```
"token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
```
=> Disabling logging of token and password as these are sensitive info

ansible/modules/hashivault/hashivault_write.py
Some backends ( like PKI ) return data when writing to them ( like PKI issue ) 
Fixes Issue #6 
This patch exposes that data as : 
```{
"changed": true, 
"data": {
"auth": null, 
"data": {
"certificate": "-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----", 
"issuing_ca": "-----BEGIN CERTIFICATE-----\n-----END CERTIFICATE-----", 
"private_key": "-----BEGIN RSA PRIVATE KEY-----\n-----END RSA PRIVATE KEY-----", 
"private_key_type": "rsa", 
"serial_number": "24:f4:za:44:ba:50:a8:97:7e:32:5"
}, 
"lease_duration": 2764799, 
"lease_id": "pki/issue/example/0bef285", 
"renewable": false, 
"request_id": "fbec62e2-ccd5-d24", 
"warnings": null, 
"wrap_info": null
}, 
"msg": "Secret pki/issue/example written", 
"rc": 0
}```
=> Return Vault data when writing to secret

ansible/modules/hashivault/hashivault_audit_enable.py, ansible/modules/hashivault/hashivault_audit_list.py, ansible/modules/hashivault/hashivault_auth_enable.py, ansible/modules/hashivault/hashivault_auth_list.py, ansible/modules/hashivault/hashivault_init.py, ansible/modules/hashivault/hashivault_list.py, ansible/modules/hashivault/hashivault_policy_delete.py, ansible/modules/hashivault/hashivault_policy_get.py, ansible/modules/hashivault/hashivault_policy_list.py, ansible/modules/hashivault/hashivault_policy_set.py, ansible/modules/hashivault/hashivault_read.py, ansible/modules/hashivault/hashivault_seal.py, ansible/modules/hashivault/hashivault_secret_disable.py, ansible/modules/hashivault/hashivault_secret_enable.py, ansible/modules/hashivault/hashivault_secret_list.py, ansible/modules/hashivault/hashivault_status.py, ansible/modules/hashivault/hashivault_unseal.py, ansible/modules/hashivault/hashivault_userpass_create.py, ansible/modules/hashivault/hashivault_userpass_delete.py, ansible/modules/hashivault/hashivault_write.py
quoted all lines in modules' documentation with colons so ansible-doc would parse them correctly.
It appears that ansible/ansible-doc is pickier about colons than most YAML parsers are.
=> quoted all lines in modules' documentation with colons so ansible-doc

ansible/modules/hashivault/hashivault_init.py, functional/run.sh, functional/test_init_config.yml
In some use cases the standard 5/3 secret share may not be desired, on initialization you are now able to set your secret sharing distribution
=> Added the ability to set shares and threshold on init

ansible/modules/hashivault/hashivault_init.py
vault supports secure initialization using public PGP keys of vault admins (Refer: https://www.vaultproject.io/api/system/init.html).
This change adds pgp_keys parameter to hashivault_init, which is transparently passed on hvac module.
=> Add support for pgp public keys during vault init

ansible/modules/hashivault/hashivault_read.py, functional/test.yml
If key is not specified, read task gets the whole secret, this is useful to compare existing with expected secrets.
=> Read task can read whole secrets

ansible/modules/hashivault/hashivault_rekey.py, ansible/modules/hashivault/hashivault_rekey_cancel.py, ansible/modules/hashivault/hashivault_rekey_init.py, ansible/modules/hashivault/hashivault_rekey_status.py, functional/run.sh, functional/test_rekey.yml
Vault supports rekey in order to change the number of key-shares, key-thresholds, PGP keys, etc. of a running Vault instance. 
Added the following modules for rekey:
- hashivault_rekey_init: Start new rekey
- hashivault_rekey: Update rekey (by providing current unseal keys)
- hashivault_rekey_cancel: Cancel a rekey in progress
- hashivault_rekey_status: Get status/progress of the on-going rekey
=> Added modules for rekey

ansible/modules/hashivault/hashivault_audit_enable.py, ansible/modules/hashivault/hashivault_auth_enable.py, ansible/modules/hashivault/hashivault_policy_delete.py, ansible/modules/hashivault/hashivault_policy_set.py, ansible/modules/hashivault/hashivault_secret_enable.py, functional/test_audit.yml, functional/test_auth.yml, functional/test_policy.yml, functional/test_rekey.yml, functional/test_secret.yml
We are starting to try this library to manage the configuration of vault and we'd like to be able to run the ansible playbook idempotently.
We have found that some tasks fail if the resource already exists (for example enabling secrets), and others run always even if the result is the same (like setting policies).
A workaround we have found is to register the state in variables and use `when`, but sometimes it's very cumbersome, or even impossible in combination with `with_items`.
I wonder if there is any reason to don't try to compare the existing with the desired state.
Find here an initial implementation of the idea for some tasks, mostly for discussion, it's not tested enough to be merged.
=> Avoid unneeded changes when possible

ansible/module_utils/hashivault.py, ansible/modules/hashivault/hashivault_audit_enable.py, ansible/modules/hashivault/hashivault_audit_list.py, ansible/modules/hashivault/hashivault_auth_enable.py, ansible/modules/hashivault/hashivault_auth_list.py, ansible/modules/hashivault/hashivault_delete.py, ansible/modules/hashivault/hashivault_init.py, ansible/modules/hashivault/hashivault_list.py, ansible/modules/hashivault/hashivault_policy_delete.py, ansible/modules/hashivault/hashivault_policy_get.py, ansible/modules/hashivault/hashivault_policy_list.py, ansible/modules/hashivault/hashivault_policy_set.py, ansible/modules/hashivault/hashivault_read.py, ansible/modules/hashivault/hashivault_rekey.py, ansible/modules/hashivault/hashivault_rekey_cancel.py, ansible/modules/hashivault/hashivault_rekey_init.py, ansible/modules/hashivault/hashivault_rekey_status.py, ansible/modules/hashivault/hashivault_seal.py, ansible/modules/hashivault/hashivault_secret_disable.py, ansible/modules/hashivault/hashivault_secret_enable.py, ansible/modules/hashivault/hashivault_secret_list.py, ansible/modules/hashivault/hashivault_status.py, ansible/modules/hashivault/hashivault_token_create.py, ansible/modules/hashivault/hashivault_token_lookup.py, ansible/modules/hashivault/hashivault_unseal.py, ansible/modules/hashivault/hashivault_userpass_create.py, ansible/modules/hashivault/hashivault_userpass_delete.py, ansible/modules/hashivault/hashivault_write.py
Adds support for using strong, (potentially) mutually-authenticated
TLS connections to Hashicorp Vault API.
Adds parameters to allow user to specify paths for client cert and
client key in order to support TLS mutual authentication with Vault
HTTP API, where the hvac client includes Python 'requests' and passes
the client cert and client key as a tuple argument to the 'cert' param
supplied to a requests.Session object. Depending on what params/values
are supplied by user, the value for 'verify' (as passed to the
requests.Session object) will be either True, False, or (preferrably)
the path to a CA cert or directory of CA certs to use for TLS auth
validation.
Updates argument_spec with new params for TLS client authentication :
-  ca_cert
-  ca_path
-  client_cert
-  client_key
Updates …
=> Adds support for TLS connections via hvac

ansible/modules/hashivault/hashivault_auth_enable.py, functional/test_auth.yml
Allows for the same auth backend to be defined with different mount points
=> Add the ability to define a mount point for Auth backends

ansible/modules/hashivault/hashivault_mount_tune.py, functional/test_secret.yml
Adds the ability to tune a mount using the module. This introduces a dependency on hvac 0.3.0, but this is not versioned in setup.py so a new install would pull latest.
=> Add mount tune module

ansible/modules/hashivault/hashivault_write.py, functional/test_secret.yml
I'd like to be able to track what was already inside vault before the launch of my playbooks...
I also refactored the method a bit.
HTH
=> Changed flag support for hashivault_write

ansible/modules/hashivault/hashivault_policy_get.py
Right now hashivault_policy_get will return with a positive return code even on a non-existent policy.  Changed the return code to fail on a non-existent policy.
=> hashivault_policy_get fail on None return

ansible/module_utils/hashivault.py
Hi,
I've noticed that despite having the option to provide client certs the option to do TLS auth is not available. This PR solves this by adding a new option called `tls` and using the underlying `auth_tls()` method.
=> Adding TLS auth option

ansible/module_utils/hashivault.py
Avoid `Invalid header value` error when `~/.vault-token` has empty line following the token, e.g. when periodic token is written to file manually using `nano` for some service user.
=> Strip Vault token read from file

README.rst
RST format wasn't making it clear which environment variables were being read. This tiny tweak fixes that, so on Github it will be formatted correctly.
=> Tweak Readme

ansible/plugins/lookup/hashivault.py
I'm only using this module for lookups in group_vars. But in my scenario, none of the certificate information was actually being collected before the module would initialize a vault client and attempt to connect to the vault server. This PR only adds lookups for cert environment variables.
=> Fix missing cert info for lookups.

ansible/module_utils/hashivault.py
This PR fixes the following error:
```
{"changed": false, "failed": true, "item": "foo", "msg": "Exception: 'Client' has no attribute 'auth_methods'", "rc": 1}
```
Docs refs:
[LDAP - Authentication / Login](https://github.com/hvac/hvac/blob/develop/docs/usage/auth_methods/ldap.rst#authentication--login)
[GitHub - Authentication / Login](https://github.com/hvac/hvac/blob/develop/docs/usage/auth_methods/github.rst#authentication--login)
=> Fix auth_methods for LDAP and GitHub

README.rst, ansible/module_utils/hashivault.py
Vault enterprise allows for segmenting youre vault into 'mini-vaults' called Namespaces. this PR allows you allows you to take advantage of HVAC 0.7s ability to inject the namespace as a http header when creating the Client object
you can specify the namespace in 2 ways:
1. as a param in your ansible play
2. as an environment variable VAULT_NAMESPACE
tested execution on vault 1.0:
1. as a param in your ansible play
2. as an environment variable VAULT_NAMESPACE
3. with VAULT_NAMESPACE=""
4. without setting VAULT_NAMESPACE or namespace in play
=> optionally include namespace as play parameter or environment var

README.rst, ansible/modules/hashivault/hashivault_delete.py, ansible/modules/hashivault/hashivault_read.py, ansible/modules/hashivault/hashivault_write.py, functional/run.sh, functional/test_ephemeral.yml, functional/test_secret_v2.yml
fix for: https://github.com/TerryHowe/ansible-modules-hashivault/issues/68
add a new parameter option: `version` that takes an integer. default `1`. include tests for CI to create kv2 engine and perform write, read, delete, then disable engine
example play
```
- name: terry howe vault write with kv2
hashivault_write:
url: vault.example.com
verify: false
token: <redacted>
secret: test2
data:
password: mypass
version: 2
namespace: my/teamnamespace/kv2
```
=> add kv engine v2 support

ansible/modules/hashivault/hashivault_userpass_user.py
The existing userpass modules are not idempotent.
For example the create module will report change on each execution, even if the user already exists. It will also overwrite the existing password, which means the playbook has to have custom checks to prevent that.
This patch should allow users to manage the userpass users with single module, and also bakes in some checks.
=> Fix idempotence issue with userpass user module.

ansible/module_utils/hashivault.py
fixes #118 
I think that it is safe to remove the `callable(attr)` conditional - nearly every reference to client in the modules is for the purpose of a making an authenticated call to the API that requires a token.
I'd also be open to implementing more logic around this, since this is really just a quick fix.
=> Fix approle auth for hvac kv2 engine

ansible/modules/hashivault/hashivault_cluster_status.py, functional/test_status.yml
Forgot to add the support of the method parameter
Also in case of http GET request vault return a json so I think hashivault doesn't have to format to string
=> Add the support for the http method and return json in case of GET method

ansible/plugins/lookup/hashivault.py
The `mount_point` option is recognized by `hashivault_read` module,
which can be used to override default `secret`. This commit gives
similar capability to `hashivault` lookup plugin.
=> Add `mount_point` option to the lookup plugin

ansible/module_utils/hashivault.py, ansible/modules/hashivault/hashivault_azure_secret_engine_config.py, ansible/modules/hashivault/hashivault_azure_secret_engine_role.py, functional/run.sh, functional/test_azure_config.yml, functional/test_azure_role.yml
this PR allows passing AnsibleModule vars:
- `required_if`
- `required_together`
- `required_one_of`
- `mutually_exclusive`
more info can be found [here](http://mobygeek.net/blog/2016/02/16/ansible-module-development-parameters/)
this PR also creates a new ansible module `hashivault_azure_secret_engine_config` which takes azure SPN creds as an input from either yaml or as a json file and configures an `azure` secret engine.
this PR also creates a new ansible module `hashivault_azure_secret_engine_role` which defines azure roles in a vault azure secret engine for dynamic credentialing
**testing**
functional/test_azure_config.yml
functional/test_azure_role.yml <- disabled due to reliance on azure credentials
https://github.com/TerryHowe/ansible-modules-hashivault/issues/129
=> drewmullen/issue-129 - azure secret engine

ansible/modules/hashivault/hashivault_auth_ldap.py, ansible/modules/hashivault/hashivault_auth_list.py, ansible/modules/hashivault/hashivault_identity_entity.py, ansible/modules/hashivault/hashivault_identity_group.py, ansible/modules/hashivault/hashivault_ldap_configure.py, functional/run.sh, functional/test_identity_group.yml
Pull request includes
- NEW- ansible/modules/hashivault/hashivault_auth_ldap.py - to configure LDAP settings
- NEW - ansible/modules/hashivault/hashivault_identity_group.py - to create, update, and delete groups
- MODIFY - ansible/modules/hashivault/hashivault_identity_entity.py - fixed a typo
=> Add modules to configure LDAP and create, update, and delete groups

ansible/modules/hashivault/hashivault_namespace.py, functional/run.sh, functional/test_namespace.yml
create and delete namespaces in vault. this is an enterprise only feature (quite a good one too!)
tests are written and included but not enabled because this repo test suite doesnt use enterprise. we can start using enterprise trial at some point. this url can be modified for newer versions: https://s3-us-west-2.amazonaws.com/hc-enterprise-binaries/vault/ent/1.1.3/vault-enterprise_1.1.3%2Bent_darwin_amd64.zip
we started using that in hvac a few weeks back: https://github.com/hvac/hvac/pull/478
=> provide module to manage namespaces (ent only)

ansible/modules/hashivault/hashivault_db_secret_engine_config.py
Signed-off-by: Damien Goldenberg <damdam.gold@gmail.com>
When in the `connection_details` there is a nested list there is an exception: `Exception: unhashable type: 'list'`
Maybe there is another way to avoid this problem
=> Fix some cases where casting raise exception

README.rst, ansible/modules/hashivault/_hashivault_mount_tune.py, ansible/modules/hashivault/hashivault_secret_engine.py, functional/test_kv2.yml
fixes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/158
options['version'] accepts an int, cast to a string to ensure idempotence checks work
test wasnt failing because was using deprecated module `hashivault_secret_enable`, resolved
=> fix idempotence check for secret_engine when version 2 is passed

ansible/modules/hashivault/hashivault_db_secret_engine_config.py
current state v desired state are not compared properly. idempotent runs of this play are failling:
CURRENT:
```
[
('connection_url', 'postgresql://{{username}}:{{password}}@'),
('root_credentials_rotate_statements', []),
('username', 'user@')
]
```
vs
DESIRED:
```
[
('username', 'user@),
('connection_url', 'postgresql://{{username}}:{{password}}@')
]
```
changing to explicitly check instead
=> fix db idempotency check

ansible/modules/hashivault/hashivault_list.py, functional/test_list.yml
I updated the hashivault_list.py to utilise client.secrets.kv.v2.list_secrets and client.secrets.kv.v1.list_secrets methods and permit specifying the version and mount point.
With the current version, we had to modify several roles to account for the metadata/ in the path when transitioning to version 2 of the Vault KV secret engine.
This version removes the need to account for metadata/ in the Ansible role allowing a more seamless transition from version 1 to version 2 of the Vault KV.
I included some logic to ensure it won't break existing roles that use metadata/.
Tests also updated to test against both version 1 and version 2 of the KV.
=> Altered hashivault_list.py to use the hvac list_secrets method

ansible/modules/hashivault/hashivault_oidc_auth_method_config.py, functional/run.sh, functional/test_oidc_auth_method_config.yml
The HVAC library currently does not support OIDC auth method configuration so I have used the Python requests library to implement this feature.
=> Add OIDC auth method config and test

ansible/modules/hashivault/_hashivault_policy_set_from_file.py, ansible/modules/hashivault/hashivault_auth_method.py, ansible/modules/hashivault/hashivault_azure_auth_config.py, ansible/modules/hashivault/hashivault_azure_auth_role.py, ansible/modules/hashivault/hashivault_azure_secret_engine_config.py, ansible/modules/hashivault/hashivault_azure_secret_engine_role.py, ansible/modules/hashivault/hashivault_db_secret_engine_config.py, ansible/modules/hashivault/hashivault_db_secret_engine_role.py
add support for check mode oh `hashivault_auth_method`
fixing idempotency checks when using namespaces on several modules. 
modules show "changed" when using `-C` even if a namespace doesnt exist yet. previously they failed because the path to check current state didnt exist (no namespace)
regarding: https://github.com/TerryHowe/ansible-modules-hashivault/issues/167
includes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/167#issuecomment-540636036
=> Check mode fix

ansible/modules/hashivault/hashivault_azure_auth_role.py, ansible/modules/hashivault/hashivault_oidc_auth_role.py, functional/run.sh, functional/test_oidc_auth_role.yml
The HVAC library currently does not support OIDC auth role configuration so I have used the Python requests library to implement this feature.
=> Add OIDC auth role and functional test

ansible/modules/hashivault/hashivault_auth_method.py
fixes: https://github.com/TerryHowe/ansible-modules-hashivault/issues/176
logic was used in auth methods / secret engines to check if a namespace pre-existed to account for check mode. part of the logic broke this method because it in fact **creates** the auth method which is what we were attempting to test
=> fix auth method

ansible/modules/hashivault/hashivault_oidc_auth_method_config.py, ansible/modules/hashivault/hashivault_oidc_auth_role.py
Since we are using the Python requests library, we need to add the `X-Vault-Namespace` header into our API calls to enable the OIDC auth method and configure roles.
=> Enable OIDC auth and role in namespaces

ansible/modules/hashivault/hashivault_auth_method.py, ansible/modules/hashivault/hashivault_secret_engine.py
Hi, i have added this value to differentiate between just created and updated secrets engine
``` YAML
---
- name: "Enable PKI Secrets Engine"
run_once: true
register: pki_engine
hashivault_secret_engine:
name: "{{ pki_path }}"
backend: "pki"
description: "My awesome PKI engine"
config: "{{ pki_config }}"
- name: Configure PKI engine
when: pki_engine is created
block:
- name: "Configure PKI Secrets Engine"
run_once: true
register: pki_engine_config
hashivault_write:
mount_point: "{{ pki_path }}"
secret: "intermediate/generate/internal"
data:
common_name: "{{ pki_common_name }}"
key_bits: "{{ key_bits | default(4096) }}"
ttl: "{{ ttl | default('43800h') }}"
- name: "........"
...
````
So in this example "Configure PKI engine" needs to be executed only when PKI secrets engine is created, but …
=> Added additional return value to auth_method and secrets_engine

ansible/modules/hashivault/hashivault_identity_group.py
When creating groups with the hashivault_identity_group module, there is a bug when creating external groups: the Vault API does not expect members when creating external groups, and defaulting to an empty array passes it as an argument. This leads to an error from the Vault API: "Exception: member entities can't be set manually for external groups".
=> Defaulting members to None when creating groups

ansible/modules/hashivault/hashivault_approle_role_secret.py
When a wrapped token is created, the response key is ```wrap_info```
Include ```cidr_list``` and ```wrap_ttl``` when ```custom_secret_id``` is not ```None```
=> When a wrapped token is created, the response key is wrap_info

functional/test_userpass_no_pass.yml
Addendum to #202: Make test description easier to understand and add a test for changing token_bound_cidrs without pass.
=> Add test for changing token_bound_cidrs without pass

ansible/module_utils/hashivault.py, ansible/modules/hashivault/hashivault_azure_auth_role.py, ansible/modules/hashivault/hashivault_azure_secret_engine_config.py, ansible/modules/hashivault/hashivault_azure_secret_engine_role.py, ansible/modules/hashivault/hashivault_db_secret_engine_config.py, ansible/modules/hashivault/hashivault_db_secret_engine_role.py, ansible/modules/hashivault/hashivault_k8s_auth_config.py
These checks are identical,
Secrets mount:
```python
try:
if (mount_point + "/") not in client.sys.list_mounted_secrets_engines()['data'].keys():
return {'failed': True, 'msg': 'secret engine is not enabled', 'rc': 1}
except:
if module.check_mode:
changed = True
else:
return {'failed': True, 'msg': 'secret engine is not enabled or namespace does not exist', 'rc': 1}
```
Auth mount:
```Python
try:
if (mount_point + "/") not in client.sys.list_auth_methods()['data'].keys():
return {'failed': True, 'msg': 'auth method is not enabled', 'rc': 1}
except:
if module.check_mode:
changed = True
else:
return {'failed': True, 'msg': 'auth mount is not enabled or namespace does not exist', 'rc': 1}
```
so I moved them in to `module_utils`, and replaced duplicates with function call
=> Centralised common logic

ansible/modules/hashivault/hashivault_pki_ca.py, ansible/modules/hashivault/hashivault_pki_cert_issue.py
Probably as the result of a copy and paste some hypens are represented
in unicode rather than ASCII. This causes problems when using a python 2
host (eg Centos 7).
=> Use ASCII hypens in documentation

ansible/module_utils/hashivault.py
This is a really simple type casting to handle number/string
comparisons. I was expecting to need to cast more things than int, but
I'm not sure what else, so just do int for now and extend it as needed.
Closes: #247
=> When doing state comparisons allow int/string mismatch

ansible/modules/hashivault/hashivault_pki_role.py
It looks like everything from the documentation except server_flag is
present in the list. It's referenced in other options so assume it's
just an ommission.
https://www.vaultproject.io/api-docs/secret/pki
=> Add server_flag to pki_role

ansible/modules/hashivault/hashivault_pki_ca.py
common_name is a required parameter of creating a CA and should be
mentioned in the docs.
=> Add common_name doc string to CA

ansible/modules/hashivault/hashivault_auth_ldap.py
use_token_groups is supported by hvac for configuring ldap. Uncommenting this option in the module and add required arguments.
=> Add support for use_token_groups in auth_ldap

ansible/modules/hashivault/hashivault_auth_ldap.py, functional/test_ldap_group.yml
Very short PR.
The goal is to fix idempotency of the module `hashivault_auth_ldap`.
The current behavior is that the changed state will be true on every run of a playbook or role using the module as long as the value for the option `group_filter` has not been set (using default).
The current default is actually not set and therefor using `None` ->https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_auth_ldap.py#L128
The documentation of the module is matching Hashicorp Vault official doc so the change was to set the default value to what would be expected.
After the fix, any run of a playbook of role using the module have a correct idempotent changed state of false if nothing was modified between the run.
=> Update default value of group_filter on hashivault_auth_ldap module

ansible/modules/hashivault/hashivault_approle_role.py, functional/test_approle.yml, makedocs.sh
Allow setting the parameter "secret_id_bound_cidrs" for an AppRole. 
While adding the parameter I found a bug: bound_cidr_list doesn't set the token_bound_cidrs parameter due to different naming. This PR includes a backwards compatible fix for the issue and adds tests.
=> Introduce AppRole parameter secret_id_bound_cidrs

ansible/modules/hashivault/hashivault_oidc_auth_method_config.py, ansible/modules/hashivault/hashivault_oidc_auth_role.py
The `hashivault_oidc` modules took the token from the params. This resulted in a `missing client token` error when running it using other auth methods, such as userpass.
This PR changes the code so that `X-Vault-Token` is set using the token from the `hashivault_auth_client` instead of from the params directly.
=> Use the Vault client's token instead of directly taking it from params

ansible/modules/hashivault/hashivault_oidc_auth_method_config.py, ansible/modules/hashivault/hashivault_oidc_auth_role.py
This pull request fixes these bugs:
- `mount_point` is ignored
- the `old_state` is always `{}`
- the logic to detect changes can fail
Changed modules:
- hashivault_oidc_auth_method_config
- hashivault_oidc_auth_role
=> Fix oidc modules

ansible/modules/hashivault/hashivault_k8s_auth_config.py
Fix typo and logic to detect changes in k8s auth config
Summary
- `kubernetes_reviewer_jwt` and `mount_point` fields do not appear in `current_state`
- `pem_keys` in `desired_state` can be `None`
=> Fix logic to detect changes in k8s auth config

ansible/modules/hashivault/hashivault_delete.py, functional/run.sh, functional/test_delete_permanent.yml
I recently found this Ansible module and found it very useful. There was only one feature missing for my use case, and it's the ability to permanently delete a secret from the vault.
In this PR, the default behavior of keeping the history, metadata, and being able to revert a change, is not affected. What I did is add a parameter to `hashivault_delete`: `permanent`. A simple boolean, defaulting to `False`, that eventually calls the `hvac` method `delete_metadata_and_all_versions`.
There's no bug/feature filed for this. If you need one, let me know, I'll create it.
=> hashivault_delete: adding ability to permanently delete secret for kv v2

ansible/modules/hashivault/hashivault_rekey_init.py, ansible/modules/hashivault/hashivault_rekey_verify.py, functional/run.sh, functional/test_rekey_verify.yml
Vault has a possibility to delay putting a rekey in effect until the new
unseal keys are verified by providing a threshold of them to the rekey
endpoint. Support this scheme in the module.
=> Support verified rekeys

ansible/modules/hashivault/hashivault_userpass.py
The example in the `hashivault_userpass` documentation was using `hashivault_userpass_create` which appears to be deprecated. Also fixes small indentation issue.
=> Update hashivault_userpass example to use newer module

ansible/modules/hashivault/hashivault_audit_list.py
Make hashivault_audit_list always return as unchanged/OK, since it never
changes Vault state. This behavior is consistent with other
reading/listing modules, e.g. hashivault_approle_role_list.
=> Fix hashivault_audit_list `changed` state

ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
This pr adds a config option for oidc provider_config.
Tested with [Google Specific configuration](https://www.vaultproject.io/docs/auth/jwt_oidc_providers#optional-google-specific-configuration)
=> Add optional provider_config dict

ansible/modules/hashivault/hashivault_list.py
Module hashivault_list don't works corectly with modern Vault servers (in my environment vault-1.6.2)
Vault don't return list of secrets for subkey path with function `client.secrets.kv.v2.read_secret_metadata`
This small playbook currently return error:
```bash
---
- hosts: localhost
roles:
- ansible-modules-hashivault
tasks:
- hashivault_write:
secret: 'list/one'
url: "https://vault.query.consul.local"
data:
tuesday: 'tuesday'
version: 2
mount_point: kv  
- hashivault_write:
secret: 'list/two'
url: "https://vault.query.consul.local"
data:
wednesday: 'threde'
version: 2
mount_point: kv
- name: List secrets in folder full path levels
hashivault_list:
secret: 'list'
url: "https://vault.query.consul.local"
mount_point: kv
version: 2
register: vault_list
- assert: { that: vault_list.rc == 0 …
```
=> Use list_secrets function by default for modern Vault versions

ansible/modules/hashivault/hashivault_list.py, ansible/modules/hashivault/hashivault_oidc_auth_method_config.py, ansible/modules/hashivault/hashivault_userpass.py
A few code style fixes.
```
$ pycodestyle --max-line-length=120 ansible
ansible/modules/hashivault/hashivault_list.py:96:5: E303 too many blank lines (2)
ansible/modules/hashivault/hashivault_oidc_auth_method_config.py:58:121: E501 line too long (124 > 120 characters)
ansible/modules/hashivault/hashivault_userpass.py:91:32: E128 continuation line under-indented for visual indent
ansible/modules/hashivault/hashivault_userpass.py:125:121: E501 line too long (121 > 120 characters)
ansible/modules/hashivault/hashivault_userpass.py:126:40: E128 continuation line under-indented for visual indent
```
=> pep8 fixes

.github/workflows/test.yml, makedocs.sh, test-requirements.txt, tox.ini
I noticed the Travis CI jobs were no longer being run. I'm not sure if you had other plans, but I created a Github actions workflow that could be used.
1. makedocs.sh was failing with latest version of ```Sphinx``` so updated to only install requirements from ansible 2.9.26 repo which restricts the version.
2. Python3.6 was failing with newer versions of pip. Rather than downgrade, updated tox version 3.24.2 and removed ```LANG```, ```LANGUAGE```, and ```LC_ALL``` from tox configuration which implicitly adds to passenv.
=> Add Github Actions Test Workflow

ansible/modules/hashivault/hashivault_k8s_auth_role.py, functional/test_k8_auth.yml, setup.py
closes #356 
Add the ```token_type``` option the ```hashivault_k8s_auth_role``` module.
Requires hvac 0.11.2 which also adds it to the k8s API via hvac/hvac#760
=> Add token_type option to k8s_auth_role

ansible/modules/hashivault/hashivault_pki_role.py
This option permits templating in allowed_domains field.
See https://www.vaultproject.io/api/secret/pki#allowed_domains_template.
=> Introduce support for PKI allowed_domains_template

ansible/modules/hashivault/hashivault_secret_engine.py
So far, the parameter cas_required was passed to hvac only when backend
"kv" was used and version parameter was equal to 2. However, using kv-v2
backend do the same as backend == kv + version == 2, but the
cas_required parameter wasn't passed to hvac.
=> Pass cas value to hvac when kv-v2 backend is used

ansible/modules/hashivault/hashivault_db_secret_engine_config.py
See here: https://www.vaultproject.io/api/secret/databases#password_policy
hashivault_db_secret_engine_config module does not work w/o it with vault 1.7
=> Adding password_policy available in newer version of vault

ansible/modules/hashivault/hashivault_pki_role.py
This module, like Vault API, accepts both lists and strings with
comma-separated values for some parameters. However, the API always
returns lists. As such, the module isn't idempotent when strings are
used because it detects data changes, although these are only type and
format changes (ie. data are sementically the same).
This change adds a note about that in pki_role module doc.
Signed-off-by: Albin Kerouanton <albinker@gmail.com>
=> Advise against strings in hashivault_pki_role params

ansible/modules/hashivault/hashivault_oidc_auth_role.py
Trying to create an jwt auth role with `hashivault_oidc_auth_role` does not work since the `role_type` is hardcoded to `oidc`. The current `role_type` definition is removed and replaced with an `argspec` which defaults to `oidc`.
=> Removed static role_type oidc

ansible/module_utils/hashivault.py
Prior to this change, it wasn't possible to update a secret stored in KV
v2 secrets engine because hashivault_read doesn't return secret's
version. This fix adds secret's metadata to the return value of
hashivault_read.
Signed-off-by: Albin Kerouanton <albinker@gmail.com>
=> Return secret version when reading kv v2 secret

ansible/modules/hashivault/hashivault_list.py
Right now to remove "metadata/" string it is using `lstrip('metadata/')` and if the path contains any letter in "metadata" it will be removed.  
lstrip() isn't the function to use but rather replace and only once.  
One example would be to use the path "metadata/dev/secret" which will become "v/secret"
=> Fix hashivault_list URL with lstrip

ansible/modules/hashivault/hashivault_db_secret_engine_config.py
Fixes #379
Vault expects the root rotation statements with the ```root_rotation_statements``` key and was treating it as a non-common or plugin specific parameter. It is still returned as ```root_credentials_rotate_statements``` so logic is needed for idempotency.
=> Fix root rotation statements in connection details

ansible/modules/hashivault/hashivault_db_secret_engine_role.py
Fix idempotency when removing non-existent db secret engine role
=> Fix hashivault_db_secret_engine_role delete idempotency

ansible/modules/hashivault/hashivault_db_secret_engine_config.py
Fixes #381 
Get current state from non-default mount points and default password_policy to empty string for idempotency check.
=> Fix db_secret_engine_config idempotency

ansible/modules/hashivault/hashivault_auth_method.py, functional/test_auth_method.yml
Resolves #382 
The list auth methods and read auth method tuning return different values for the default_lease_ttl and max_lease_ttl when the user configures them as "0". The list method will return "0" but the read auth method tuning will return the effective values (the default_lease_ttl and max_lease_ttl in the server configuration). The Vault UI also uses the values from the list auth methods to display the auth method configurations rather than the read auth method tuning.
=> Fix auth_method idempotency

ansible/modules/hashivault/hashivault_token_role.py, functional/run.sh, functional/test_token_role.yml, functional/test_token_role_check_mode.yml
This module facilitates creating, updating and deleting roles in a
specified token auth engine.
This module supports check and diff mode to allow verifying potential
changes before actually applying them.
The code in this commit has been formatted with `black`.
=> add a hashivault_token_role module

ansible/modules/hashivault/hashivault_token_role_list.py, functional/test_token_role.yml, functional/test_token_role_check_mode.yml
This module lists roles configured in a specified token auth engine.
This module supports check mode (even though it does not perform any
write operations) to ensure a whole playbook can run in check mode and
proper data is still returned from this module for further tasks to use.
The code in this commit has been formatted with `black`.
=> add a hashivault_token_role_list module

ansible/modules/hashivault/hashivault_ssh_role.py, ansible/modules/hashivault/hashivault_ssh_role_list.py, functional/run.sh, functional/test_ssh_role.yml, functional/test_ssh_role_check_mode.yml
Those modules support creating, updating, deleting and listing roles in a specified ssh secrets engine.
Both diff and check mode are supported.
Code formatted with `black`.
HVAC doesn't support SSH engine natively yet so some workarounds are used. It may be available soon thanks to this [PR](https://github.com/hvac/hvac/pull/811).
=> add hashivault_ssh_role and hashivault_ssh_role_list modules

ansible/modules/hashivault/hashivault_auth_ldap.py, functional/test_ldap_group.yml
hashivault_auth_ldap always returns as changed because the desired state token_ttl/token_max_ttl are strings whereas in the current state they are ints.
Fixes this by correcting the type.
I believe this corrects #393
Unrelated silly questyon but I see that the module now requires Ansible >=4 and was wondering why that might be? It seems to work find on 2.9
=> Fixup idempotency of hashivault_auth_ldap

ansible/module_utils/hashivault.py, ansible/modules/hashivault/hashivault_pki_role.py
This is a proposed mitigation to #426. Instead of copying known arguments to the desired_state, we copy all arguments, while normalizing the ones we know about.
I have extracted that function to module_utils because if that change is accepted, it's probably worth applying it to all modules. This is obviously just a stop gap measure, adding the new parameters is preferred, but seeing the low release frequency, this will avoid blocking users for a long time.
I can try and add some warning if the parameter is not found in the doc, that could help users identify typos and report missing fields.
WDYT?
=> Extract option normalisation to module_utils and reverse logic to allow for unknown options

ansible/modules/hashivault/hashivault_approle_role_secret.py
Currently `hashivault_approle_role_secret` return plain response from underlying library. `data` field with response from the vault.
Examples and other modules (hashivault_approle_role_id) assumed that result would contain `id` field with corresponding value.
=> Fix output hashivault_approle_role_secret format

ansible/module_utils/hashivault.py, ansible/plugins/doc_fragments/hashivault.py
This would be useful. Default value of 30, [as it is in hvac](https://hvac.readthedocs.io/en/stable/source/hvac_v1.html#hvac.v1.Client.__init__), to prevent inconsistency.
=> Add timeout for all modules

ansible/modules/hashivault/hashivault_pki_role.py
As discussed in #449, the type needs to be `list` instead of `type`.
=> Fix wrong type (#449)

ansible/module_utils/hashivault.py
#457 HVAC 1.0.0+ have all authentication methods as subclasses of client.auth
Update login code to call the appropriate subclass for tls/cert auth
=> Fix issue #457

ansible/modules/hashivault/hashivault_jwt_auth_method_config.py, ansible/modules/hashivault/hashivault_jwt_auth_role.py, functional/run.sh, functional/test_jwt_auth_method_config.yml, functional/test_jwt_auth_role.yml
=> Add support for JWT role

ansible/modules/hashivault/hashivault_write.py
The write_data method allows the user to store data named `path` and `wrap_ttl`
=> chore: Use write_data method

ansible/modules/hashivault/hashivault_pki_role_list.py, functional/test_pki.yml
With this change in place data can be read in check mode
=> Add check_mode support to hashivault_pki_role_list

ansible/module_utils/hashivault.py, ansible/modules/hashivault/hashivault_pki_role.py, ansible/modules/hashivault/hashivault_secret_engine.py, functional/test_pki.yml
As in the title, allows to run the playbooks with `--diff --check` combination to see what the changes would be without actually applying them.
While at it also updates the list of supported options, based on Vault API docs.
The tricky part here is that "durations" sent to Vault are required to be strings, while GET responses return integers.
Thus a temporary "view" of the desired state is created to converge on the same format.
Reuses (and moves to `module_utils`) the `parse_duration` function originally introduced in https://github.com/TerryHowe/ansible-modules-hashivault/commit/721fd555a7ce6b43b81033bb65611ecc84e69ddf . The temporary object is necessary here as Vault API doesn't officially support POSTing integers for this endpoint.
=> Add diff mode support to hashivault_pki_role and update options list

ansible/modules/hashivault/hashivault_k8s_auth_config.py
Hello,
this change allows setting the disable_local_ca_jwt flag in the k8s auth config. It's required when vault is running in a k8s cluster but you want to use the request token to do the full auth.
official doc for that flag is here https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#disable_local_ca_jwt
=> add disable_local_ca_jwt param in k8s auth config

ansible/modules/hashivault/hashivault_auth_ldap.py
=> Add support for token_bound_cidrs to hashivault_auth_ldap
